# Generated by Django 4.2 on 2023-12-06 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationEngineer',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.location')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.engineer')),
            ],
            bases=('data.location',),
        ),
        migrations.DeleteModel(
            name='Visits',
        ),
    ]
