# Generated by Django 4.2 on 2023-12-06 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_locationengineer_delete_visits'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationClient',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.location')),
            ],
            bases=('data.location',),
        ),
    ]
