# Generated by Django 4.2 on 2023-12-06 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_locationclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationclient',
            name='engineer_visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.engineer'),
        ),
    ]
