# Generated by Django 4.2 on 2023-12-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_locationclient_engineer_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='unique_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
