# Generated by Django 4.2 on 2023-12-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_engineer_unique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='unique_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
